/**
 * Created by danding on 17/2/5.
 */
module.exports={
    WRITE_FILE_DATA:' WRITE_FILE_DATA',
    SAVE_SUCCESSFUL:'SAVE_SUCCESSFUL',
    ON_FILE_DATA:'ON_FILE_DATA',
    GET_FILE_DATA:'GET_FILE_DATA',
    GET_FILE_METADATA:'GET_FILE_METADATA',
    RENAME:'RENAME',
    CREATE_DIRECTORY:'CREATE_DIRECTORY',
    CREATE_FILE:'CREATE_FILE',
    ADD_SUB_PATH:'ADD_SUB_PATH',
    ADD_SUB_PATH_BATCH:'ADD_SUB_PATH_BATCH',
    REMOVE_SUB_PATH:'REMOVE_SUB_PATH',
    REMOVE_SUB_PATH_BATCH:'REMOVE_SUB_PATH_BATCH'
}
