/**
 * Created by danding on 17/2/5.
 */
module.exports={
    RUN_SIMULATOR:'RUN_SIMULATOR',
    STOP_PACKAGER:'STOP_PACKAGER',
    RUN_PACKAGER:'RUN_PACKAGER',
    RESUME_PACKAGER:'RESUME_PACKAGER',
    RESUME_SIMULATOR:'RESUME_SIMULATOR',
    LIST_AVAILABLE_SIMS:'LIST_AVAILABLE_SIMS',
    HARD_RELOAD_SIMULATOR:'HARD_RELOAD_SIMULATOR'
};
